config/routes.rb
Tennisrunde::Application.routes.draw do
 
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match 'events/:id/status_update' => 'events#status_update', :as => :status_update
  
  root :to => "calendar#index"
  
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "players#new", :as => "signup"
  
  resources :players
  resources :sessions
  resources :events
  resources :matchdates
  

end

app/models/player.rb
# encoding: UTF-8
class Player < ActiveRecord::Base
	
	validates :password, :firstname, :lastname, :email, :presence => {:on => :create}
	validates_uniqueness_of	:email
	
	has_secure_password
	has_many :events, :dependent => :destroy
	
	def name
		self.firstname + ' ' + self.lastname
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
	before_filter :authenticate_user!
	
	def new
  	  @player = Player.new({
  	  	:firstname => 'Max',
  	  	:lastname => 'Mustermann',
  	  	:email => 'max@mustermann.de',
  	  	:phone => '02305/123456',
  	  	:is_admin => true,
  	  	:is_guestplayer => false,
  	  	:mobile => '0171/12345678'})
  end

  def create
  	  @player = Player.new(params[:player])
  	  if @player.save
  	  	  redirect_to root_url, :notice => "Neuer Spieler #{@player.name} wurde angelegt!"
  	  else
  	  	  render "new"
  	  end
  end
  
  def index
  	  @players = Player.all	  
  end
  
  def destroy
  	@player = Player.find(params[:id])
    @player.destroy
    redirect_to root_url, :notice => "Der Spieler #{@player.name} wurde gel&ouml;scht!".safe_html
  end
  
  # GET /players/1/edit
  def edit
  	  @player = Player.find(params[:id])
  end
  
  # PUT /players/1
  # PUT /players/1.json
  def update
  	@player = Player.find(params[:id])

    respond_to do |format|
    	if @player.update_attributes(params[:player])
    	format.html { redirect_to players_path, notice: "#{@player.name} wurde bearbeitet!" }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  <% if @player.errors.any? %>
    <div class="error_messages">
      <h2>Fehlerhafte Daten</h2>
      <ul>
        <% for message in @player.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :firstname, 'Vorname' %>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname, 'Nachname' %>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :phone, 'Festnetz' %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :mobile, 'Handy' %>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Passwort" %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
  	<%= f.label :password_confirmation, "Passwort-Wiederholung" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :is_admin, 'Admin' %>
    <%= f.check_box :is_admin %>
  </div>
    <div class="field">
    <%= f.label :is_guestplayer, 'Gastspieler' %>
    <%= f.check_box :is_guestplayer %>
  </div>
  <div class="actions"><%= f.submit "Speichern" %></div>
<% end %>

app/views/players/create.html.erb
<h1>Players#create</h1>
<p>Find me in app/views/players/create.html.erb</p>

app/views/players/edit.html.erb
<h1>Spieler bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Spielerliste', players_path %>

app/views/players/index.html.erb
<h1>Spielerliste</h1>
	<%= link_to "Neuer Spieler", new_player_path %> | <%= link_to "Spielplan", root_path %>
	<br /><br />
<table class="list">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Telefon</th>
    <th>Mobil</th>
    <th>Admin</th>
    <th>Gast</th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.firstname + ' ' + player.lastname %></td>
    <td><%= player.email %></td>
    <td><%= player.phone %></td>
    <td><%= player.mobile %></td>
    <td><%= player.is_admin ? 'ja' : 'nein' %></td>
    <td><%= player.is_guestplayer ? 'ja' : 'nein' %></td>
    <td><%= link_to "L&ouml;schen".html_safe, player, :confirm => 'Are you sure?', :method => :delete %> | <%= link_to 'Bearbeiten', edit_player_path(player) %></td>
  </tr>
<% end %>
</table>

app/views/players/new.html.erb
<h1>Neuer Spieler</h1>

<%= render 'form' %>

<%= link_to 'Spielerliste', root_path %>